apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whoami
  namespace: gateway-demo
spec:
  parentRefs:
  - name: demo-gw
    namespace: kube-system
  hostnames:
  - "demo-gw-whoami.microherd.local"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: whoami
      port: 80
